version: "3"
services:
  app:
    container_name: node
    build: ./docker/app
    volumes:
      - ${APP_CODE_PATH_HOST}:/app
    tty: true
    environment:
      TZ: Asia/Tokyo

  nginx:
    container_name: ts-nginx
    build:
        context: ./docker/nginx
    volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
        - app
